# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew installDDist
    - name: Build and push Docker
      uses: docker/build-push-action@v2.1.0
      with:
        tags: docker.pkg.github.com/gillesbraun/ts3clientnotify/ts3clientnotify:latest
        github-token: ${{ secrets.REPOSITORY_PUSH_TOKEN }}
        push: true
