# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build Docker
      uses: docker/build-push-action@v2
      with:
        tags: docker.pkg.github.com/gillesbraun/ts3clientnotify/ts3clientnotify:latest
    - name: Push Docker Image
      run: docker push docker.pkg.github.com/gillesbraun/ts3clientnotify/ts3clientnotify:latest
