# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew installDist
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push Docker
      uses: docker/build-push-action@v2
      with:
        tags: ${{ env.REGISTRY }}y/ts3clientnotify:latest
        push: true
    - name: Push
      run: docker push ${{ env.REGISTRY }}/ts3clientnotify:latest
